development: &default
  adapter: postgresql
  database: odeskjob_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 20
  timeout: 5000

test:
  <<: *default
  database: odeskjob_test

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>